bugheist/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

import comments.views
import website.views
from website.views import (UserProfileDetailView, IssueCreate, UploadCreate, EmailDetailView,
                           InboundParseWebhookView, LeaderboardView, IssueView, AllIssuesView, SpecificIssuesView,                            HuntCreate, DomainDetailView, StatsDetailView, InviteCreate, CreateInviteFriend,
                           ScoreboardView)

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

admin.autodiscover()

urlpatterns = [
                  url(r'^$', website.views.index, name='index'),
                  url(r'^' + settings.ADMIN_URL + '/', include(admin.site.urls)),
                  url(r'^like_issue/(?P<issue_pk>\d+)/$', website.views.like_issue, name="like_issue"),
                  url(r'^save_issue/(?P<issue_pk>\d+)/$', website.views.save_issue, name="save_issue"),
                  url(r'^unsave_issue/(?P<issue_pk>\d+)/$', website.views.unsave_issue, name="unsave_issue"),
                  url(r'^issue/edit/$', website.views.IssueEdit),
                  url(r'^issue/update/$', website.views.UpdateIssue),
                  url(r'^issue/(?P<slug>\w+)/$', IssueView.as_view(), name="issue_view"),
                  url(r'^follow/(?P<user>[^/]+)/', website.views.follow_user,name="follow_user"),
                  url(r'^all_activity/$', AllIssuesView.as_view(), name="all_activity"),
                  url(r'^label_activity/$', SpecificIssuesView.as_view(), name="all_activity"),
                  url(r'^leaderboard/$', LeaderboardView.as_view(), name="leaderboard"),
                  url(r'^scoreboard/$', ScoreboardView.as_view(), name="scoreboard"),
                  url(r'^issue/$', IssueCreate.as_view(), name="issue"),
                  url(r'^upload/(?P<time>[^/]+)/(?P<hash>[^/]+)/',
                      UploadCreate.as_view(), name="upload"),
                  url(r'^profile/(?P<slug>[^/]+)/$',
                      UserProfileDetailView.as_view(), name="profile"),
                  url(r'^domain/(?P<slug>[^/]+)/$',
                      DomainDetailView.as_view(), name="domain"),
                  url(r'^email/(?P<slug>[^/]+)/$', EmailDetailView.as_view(), name="email"),
                  url(r'^.well-known/acme-challenge/(?P<token>[^/]+)/$',
                      website.views.find_key, name="find_key"),
                  url(r'^accounts/profile/', website.views.profile),
                  url(r'^delete_issue/(?P<id>\w+)/$', website.views.delete_issue),
                  url(r'^accounts/', include('allauth.urls')),
                  url(r'^start/$', TemplateView.as_view(template_name="hunt.html")),
                  url(r'^hunt/$', login_required(HuntCreate.as_view()), name="hunt"),
                  url(r'^invite/$', InviteCreate.as_view(template_name="invite.html")),
                  url(r'^invite-friend/$', login_required(CreateInviteFriend.as_view()),
                      name='invite_friend'),
                  url(r'^terms/$', TemplateView.as_view(template_name="terms.html")),
                  url(r'^about/$', TemplateView.as_view(template_name="about.html")),
                  url(r'^stats/$', StatsDetailView.as_view()),
                  url(r'^favicon\.ico$', favicon_view),
                  url(r'^sendgrid_webhook/$', csrf_exempt(InboundParseWebhookView.as_view()),
                      name='inbound_event_webhook_callback'),
                  url(r'^issue/comment/add/$', comments.views.add_comment, name='add_comment'),
                  url(r'^issue/comment/delete/$',
                      comments.views.delete_comment, name='delete_comment'),
                  url(r'^comment/autocomplete/$',
                      comments.views.autocomplete, name='autocomplete'),
                  url(r'^issue/(?P<pk>\d+)/comment/edit/$',
                      comments.views.edit_comment, name='edit_comment'),
                  url(r'^issue/(?P<pk>\d+)/comment/reply/$',
                      comments.views.reply_comment, name='reply_comment'),
                  url(r'^social/$', TemplateView.as_view(template_name="social.html")),
                  url(r'^search/$', website.views.search),
                  url(r'^report/$', TemplateView.as_view(template_name="report.html")),
                  url(r'^i18n/', include('django.conf.urls.i18n')),
                  url(r'^domain_check/$', website.views.domain_check),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

comments/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from website.models import Issue


# Create your models here.

class Comment(models.Model):
    parent = models.ForeignKey('self', null=True)
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    author_url = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

    def children(self):
        return Comment.objects.filter(parent=self)

website/models.py
import os
from urlparse import urlparse

import requests
import tweepy
from PIL import Image
from annoying.fields import AutoOneToOneField
from colorthief import ColorThief
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.db import models
from django.db.models import Count
from django.db.models import signals
from django.db.models.signals import post_save
from unidecode import unidecode


class Domain(models.Model):
    name = models.CharField(max_length=255, unique=True)
    url = models.URLField()
    logo = models.ImageField(upload_to="logos", null=True, blank=True)
    webshot = models.ImageField(upload_to="webshots", null=True, blank=True)
    clicks = models.IntegerField(null=True, blank=True)
    email_event = models.CharField(max_length=255, default="", null=True, blank=True)
    color = models.CharField(max_length=10, null=True, blank=True)
    github = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    twitter = models.CharField(max_length=30, null=True, blank=True)
    facebook = models.URLField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name

    @property
    def open_issues(self):
        return Issue.objects.filter(domain=self).exclude(status="closed")

    @property
    def closed_issues(self):
        return Issue.objects.filter(domain=self).filter(status="closed")

    @property
    def top_tester(self):
        return User.objects.filter(issue__domain=self).annotate(total=Count('issue')).order_by('-total').first()

    @property
    def get_name(self):
        parsed_url = urlparse(self.url)
        return parsed_url.netloc.split(".")[-2:][0].title()

    def get_logo(self):
        if self.logo:
            return self.logo.url
        image_request = requests.get("https://logo.clearbit.com/" + self.name)
        try:
            if image_request.status_code == 200:
                image_content = ContentFile(image_request.content)
                self.logo.save(self.name + ".jpg", image_content)
                return self.logo.url

        except:
            favicon_url = self.url + '/favicon.ico'
            return favicon_url

    @property
    def get_color(self):
        if self.color:
            return self.color
        else:
            if not self.logo:
                self.get_logo()
            try:
                color_thief = ColorThief(self.logo)
                self.color = '#%02x%02x%02x' % color_thief.get_color(quality=1)
            except:
                self.color = "#0000ff"
            self.save()
            return self.color

    @property
    def hostname_domain(self):
        parsed_url = urlparse(self.url)
        return parsed_url.hostname

    @property
    def domain_name(self):
        parsed_url = urlparse(self.url)
        domain = parsed_url.hostname
        temp = domain.rsplit('.')
        if (len(temp) == 3):
            domain = temp[1] + '.' + temp[2]
        return domain

    def get_absolute_url(self):
        return "/domain/" + self.name


def validate_image(fieldfile_obj):
    filesize = fieldfile_obj.file.size
    megabyte_limit = 3.0
    if filesize > megabyte_limit * 1024 * 1024:
        raise ValidationError("Max file size is %sMB" % str(megabyte_limit))


class Issue(models.Model):
    labels = (
        (0, 'General'),
        (1, 'Number Error'),
        (2, 'Functional'),
        (3, 'Performance'),
        (4, 'Security'),
        (5, 'Typo'),
        (6, 'Design')
    )
    user = models.ForeignKey(User, null=True, blank=True)
    domain = models.ForeignKey(Domain, null=True, blank=True)
    url = models.URLField()
    description = models.TextField()
    label = models.PositiveSmallIntegerField(choices=labels, default=0)
    views = models.IntegerField(null=True, blank=True)
    status = models.CharField(max_length=10, default="open", null=True, blank=True)
    user_agent = models.CharField(max_length=255, default="", null=True, blank=True)
    ocr = models.TextField(default="", null=True, blank=True)
    screenshot = models.ImageField(upload_to="screenshots", validators=[validate_image])
    closed_by = models.ForeignKey(User, null=True, blank=True, related_name="closed_by")
    closed_date = models.DateTimeField(default=None, null=True, blank=True)
    github_url = models.URLField(default="", null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.description

    @property
    def domain_title(self):
        parsed_url = urlparse(self.url)
        return parsed_url.netloc.split(".")[-2:][0].title()

    @property
    def hostname_domain(self):
        parsed_url = urlparse(self.url)
        return parsed_url.hostname

    @property
    def domain_name(self):
        parsed_url = urlparse(self.url)
        domain = parsed_url.hostname
        temp = domain.rsplit('.')
        if (len(temp) == 3):
            domain = temp[1] + '.' + temp[2]
        return domain

    def get_twitter_message(self):
        issue_link = " bugheist.com/issue/" + str(self.id)
        prefix = "Bug found on @"
        spacer = " | "
        msg = prefix + self.domain_title + spacer + self.description[:140 - (
            len(prefix) + len(self.domain_title) + len(spacer) + len(issue_link))] + issue_link
        return msg

    def get_ocr(self):
        if self.ocr:
            return self.ocr
        else:
            try:
                import pytesseract
                self.ocr = pytesseract.image_to_string(Image.open(self.screenshot))
                self.save()
                return self.ocr
            except:
                return "OCR not installed"

    @property
    def get_absolute_url(self):
        return "/issue/" + str(self.id)

    class Meta:
        ordering = ['-created']


TWITTER_MAXLENGTH = getattr(settings, 'TWITTER_MAXLENGTH', 140)


def post_to_twitter(sender, instance, *args, **kwargs):
    if not kwargs.get('created'):
        return False
    try:
        consumer_key = os.environ['TWITTER_CONSUMER_KEY']
        consumer_secret = os.environ['TWITTER_CONSUMER_SECRET']
        access_key = os.environ['TWITTER_ACCESS_KEY']
        access_secret = os.environ['TWITTER_ACCESS_SECRET']
    except KeyError:
        print 'WARNING: Twitter account not configured.'
        return False

    try:
        text = instance.get_twitter_message()
    except AttributeError:
        text = unicode(instance)

    mesg = u'%s' % (text)
    if len(mesg) > TWITTER_MAXLENGTH:
        size = len(mesg + '...') - TWITTER_MAXLENGTH
        mesg = u'%s...' % (text[:-size])

    import logging
    logger = logging.getLogger('testlogger')

    if not settings.DEBUG:
        try:
            auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
            auth.set_access_token(access_key, access_secret)
            api = tweepy.API(auth)
            file = default_storage.open(instance.screenshot.file.name, 'rb')
            media_ids = api.media_upload(filename=unidecode(instance.screenshot.file.name), file=file)
            params = dict(status=mesg, media_ids=[media_ids.media_id_string])
            api.update_status(**params)

        except Exception, ex:
            print 'ERROR:', str(ex)
            logger.debug('rem %s' % str(ex))
            return False


signals.post_save.connect(post_to_twitter, sender=Issue)


class Hunt(models.Model):
    user = models.ForeignKey(User)
    url = models.URLField()
    prize = models.IntegerField()
    logo = models.ImageField(upload_to="logos", null=True, blank=True)
    plan = models.CharField(max_length=10)
    txn_id = models.CharField(max_length=50, null=True, blank=True)
    color = models.CharField(max_length=10, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    @property
    def domain_title(self):
        parsed_url = urlparse(self.url)
        return parsed_url.netloc.split(".")[-2:][0].title()

    class Meta:
        ordering = ['-id']


class Points(models.Model):
    user = models.ForeignKey(User)
    issue = models.ForeignKey(Issue, null=True, blank=True)
    domain = models.ForeignKey(Domain, null=True, blank=True)
    score = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


# @receiver(user_logged_in, dispatch_uid="some.unique.string.id.for.allauth.user_logged_in")
# def user_logged_in_(request, user, **kwargs):
#    if not settings.TESTING:
#    	action.send(user, verb='logged in')


class InviteFriend(models.Model):
    sender = models.ForeignKey(User)
    recipient = models.EmailField()
    sent = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-sent',)
        verbose_name = 'invitation'
        verbose_name_plural = 'invitations'


def user_images_path(instance, filename):
    from django.template.defaultfilters import slugify
    filename, ext = os.path.splitext(filename)
    return 'avatars/user_{0}/{1}{2}'.format(instance.user.id, slugify(filename), ext)


class UserProfile(models.Model):
    title = (
        (0, 'Unrated'),
        (1, 'Bronze'),
        (2, 'Silver'),
        (3, 'Gold'),
        (4, 'Platinum'),
    )
    follows = models.ManyToManyField('self', related_name='follower', symmetrical=False, blank=True)
    user = AutoOneToOneField('auth.user', related_name="userprofile")
    user_avatar = models.ImageField(upload_to=user_images_path, blank=True, null=True)
    title = models.IntegerField(choices=title, default=0)

website/forms.py
from django import forms

from .models import InviteFriend, UserProfile


class FormInviteFriend(forms.ModelForm):
    class Meta:
        model = InviteFriend
        fields = ['recipient']
        widgets = {'recipient': forms.TextInput(attrs={'class': 'form-control'})}


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('user_avatar',)

website/templates/_activity.html
{% load gravatar %}
<div class="list-group-item activity-strip">
    <div class="activity-strip-section">
        {% if activity.user.socialaccount_set.all.0.get_avatar_url %}
            <img src="{{ activity.user.socialaccount_set.all.0.get_avatar_url }}" width="100"
                 class="img-responsive img-rounded">
        {% else %}
            <img src="{% gravatar_url activity.user.email 100 %}" width="100" class="img-responsive img-rounded">
        {% endif %}

        <div class="info">
            <a href="/domain/{{ activity.domain_name }}">
                <img src="http://www.{{ activity.domain_name }}/favicon.ico" height="25"
                     onerror="this.onerror=null; this.style.display='none';">
            </a>
            <a href="{{ activity.get_absolute_url }}">{{ activity.description|truncatechars:30 }}</a>
            {% if activity.status == "open" %}
                <span class="label label-success text-capitalize">{{ activity.status }}</span>
            {% else %}
                <span class="label label-danger text-capitalize">{{ activity.status }}</span>
            {% endif %}
            <span class="label label-info bug-type">{{ activity.get_label_display }}</span>
            <div class="small">
                <a href="{{ activity.user.get_absolute_url }}" data-toggle="popover"
                   data-tag="{{ activity.user.userprofile.get_title_display }}">
                    {{ activity.user|default:"Anonymous" }}
                </a>
                found a bug on <a
                    href="/domain/{{ activity.domain_name }}">{{ activity.domain_title }}</a> {{ activity.created|timesince }}
                ago
            </div>
            <a class="comment_link" href="{{ activity.get_absolute_url }}#comments">
                {{ activity.comments.all|length }} comments
            </a>
        </div>
    </div>
    <div class="activity-screenshot">
        {% if activity.screenshot %}
            <a href="{{ activity.get_absolute_url }}">
                <img src="{{ activity.screenshot.url }}">
            </a>
        {% endif %}
    </div>
</div>

website/templates/_featured.html
{% comment %}
     {% for hunt in hunts %}
        <div class="col-lg-6 col-md-6">
            <div class="panel" id="hunt_{{domain.id}}" style="background-color:{{domain.get_color}}">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3  image_container">
                            <img src="{{MEDIA_URL}}{{domain.logo}}" id="hunt_image{{domain.id}}"
                            onerror="this.onerror=null; this.style.display='none';" height="75" width="75">
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge"><span><a href="/domain/{{domain.name}}/">{{domain.get_name}}</a></span></div>
                            <div>{% if domain.prize %}Grand Prize ${{domain.prize}}{% endif %}</div>
                        </div>
                    </div>
                    <div class="row issue_count">
                        <div class="col-xs-12 text-right">
                            Issues 
                            <span>
                                <a href="/domain/{{domain.name}}/#open">Open {{domain.open_issues.count}}</a>
                            </span>
                            <span>
                                <a href="/domain/{{domain.name}}/#closed"> Closed {{domain.closed_issues.count}}</a>
                            </span>
                        </div>
                    </div>
                </div>
                <a href="{{domain.url}}" target="_new">
                    <div class="panel-footer">
                        <span class="pull-left" id="hunt_link{{domain.id}}" style="color:{{domain.get_color}}">View Website</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right" id="hunt_icon{{domain.id}}" style="color:{{domain.get_color}}"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
    {% endfor %}
{% endcomment %}

<div class="col-lg-12 col-md-12">
    <div class="panel owasp-panel">
        <div class="panel-heading" style="color:#fff">
            <div class="row">
                <div class="col-xs-3 image_container">
                    <img src="https://www.owasp.org/images/thumb/2/2f/Owasp_logo_flat2_icon.jpg/100px-Owasp_logo_flat2_icon.jpg"
                         width="75" height="75">
                </div>
                <div class="col-xs-8 col-xs-offset-1">
                    On OWASP.org - testing and reporting all of the salesforce integrations with webforms, and webform
                    data on the website.
                    Get a complete list of all of the forms in use which we can pull from the chapter (leaders)
                    handbook, and the current site.
                    test each one and file bug reports for them. In particular, each form should be able to do the
                    following:
                    Receive the post data accurately
                    Return to the user's browser the confirmation that it was received on the screen when submitted
                    along with an issue number.
                    Issu8 a receipt to the user via email with complete data submitted by the form. If there is credit
                    card info or personal info, it should be only partial but enough to verify that it was included in
                    the submission.
                    There should be a timeline or some kind of data that the user receives in the email to expect a
                    resolution of their issue, and the forms should be logged in a place where the user can access the
                    log data through their account, as well as tracked on the resolution and progress of the issue's
                    progress.
                </div>
                <div class="col-xs-12 text-right">
                    <strong>OWASP Grand Prize $100</strong>
                </div>
            </div>
            <div class="row issue_count">
                <div class="col-xs-12 text-right">
                    <span>
                        <a href="/domain/owasp.org/#open">Open {{ open_issue_owasp }}</a>
                    </span>
                    <span>
                        <a href="/domain/owasp.org/#closed">Closed {{ closed_issue_owasp }}</a>
                    </span>
                </div>
            </div>
        </div>
        <a href="https://www.owasp.org/index.php/Bug_Bounty_Projects" target="_new">
            <div class="panel-footer">
                <span class="pull-left" style="color:#234082">View Website</span>
                <span class="pull-right">
                    <i class="fa fa-arrow-circle-right" style="color:#234082"></i>
                </span>
                <div class="clearfix"></div>
            </div>
        </a>
    </div>
</div>

website/templates/_followers.html
{% load gravatar %}
<div class="list-group">
    {% for user in followers %}
        <div class="list-group-item">
            {% if user.socialaccount_set.all.0.get_avatar_url %}
                <img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" height="50px">
            {% else %}
                <img src="{% gravatar_url user.email 50 %}">
            {% endif %}
            <a href="/profile/{{ user.username }}">{{ user.username }}</a>
        </div>
    {% endfor %}
</div>

website/templates/_following.html
{% load gravatar %}
<div class="list-group">
    {% for user in following %}
        <div class="list-group-item">
            {% if user.socialaccount_set.all.0.get_avatar_url %}
                <img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" height="50px">
            {% else %}
                <img src="{% gravatar_url user.email 50 %}">
            {% endif %}
            <a href="/profile/{{ user.username }}">{{ user.username }}</a>
        </div>
    {% endfor %}
</div>

website/templates/about.html
{% extends "base.html" %}
{% load gravatar %}
{% load staticfiles %}
{% load humanize %}



{% block content %}

    <div class="row">
        <div class="col-lg-6">
            <h1>About BugHeist</h1>
            <p>Software code allows us to buy a gift for Mom or Dad on amazon.com in 7 seconds, watch our favorite
                “House of Cards” episode on Netflix or read Yelp reviews about a new restaurant.</p>

            <p>When we can’t access the information we’re looking for on the internet within seconds, <i>we are not
                happy.</i>
            <p>

            <p>This is where you come into the picture.</p>

            <p>BugHeist wants you to identify the software (and hardware) bugs that delay downloads, freeze screens,
                create payloads that deliver malware to websites and generate other issues.</p>

            <h2><strong>What’s in it for you?</strong></h2>
            <ul>
                <li>Points.</li>
                <li>Money if you join a BugHeist Sponsored Bug Hunt.</li>
                <li>Jackpot money listed on the Leaderboard.</li>
                <li>Money if someone tips you for finding a bug through the tip button.</li>
                <li>Experience to add to your résumé or portfolio.</li>
            </ul>

            <h3><strong>How it Works</strong></h3>

            <h4><strong>Testers</strong></h4>
            <ol>
                <li>Create a User Account to log into BugHeist.</li>
                <li>Describe the software or hardware bug you found.</li>
                <li>Attach a screenshot of the bug.</li>
                <li>Submit the information.</li>
                <li>Win money through company-sponsored Bug Hunts, tips or the Grand Prize/Jackpot.We may also have
                    "heists" where each bug is worth a specific amount based on what the company sets.
                </li>
                <li>If you participate in BugHeist’s sponsored Bug Hunts, you could win prize money known as tips.</li>
            </ol>

            <h4><strong>Organizations</strong></h4>

            We want everyone to love your website.
            <p>You want to keep your customers happy by giving them a consistent bug-free user experience. BugHeist
                offers monthly Bug Hunts through 4 different subscription plans to help you achieve this.</p>

            <h1>Subscriptions:</h1>
        </div>
    </div>

    {% include '_subscriptions.html' %}

    <div class="row">
        <div class="col-lg-12">
            <h3>Want to kick the tires before you make a purchase? BugHeist shares up to 5 software bugs fee-free
                through a Trial Bug Hunt.</h3>
            Test-drive BugHeist here <a href="/hunt" class="btn btn-primary submit_button">Start</a>
        </div>
    </div>
{% endblock %}

website/templates/followers.html
{% if request.user != user and request.user.is_authenticated %}
    {% if request.user.email in followers_list %}
        <a class="follow_unfollow btn btn-default" name="{{ user }}">Unfollow</a>
    {% else %}
        <a class="follow_unfollow btn btn-default" name="{{ user }}">Follow</a>
    {% endif %}
{% endif %}

<div class="status">
    <form name="_xclick" action="https://www.paypal.com/cgi-bin/webscr" method="post">
        <input type="hidden" name="cmd" value="_xclick">
        <input type="hidden" name="business" value="{{ project.paypal|default:"coderbounty@gmail.com" }}">
        <input type="hidden" name="item_name" value="tip for {{ user.username }} on bugheist.com">
        <input type="hidden" name="currency_code" value="USD">
        <button type="submit" class="btn btn-danger">
            <i class="fa fa-money fa-lg"></i> Send a tip
        </button>
    </form>
</div>

website/templates/invite.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-lg-10">
            {% if exists %}
                <p>Click <a
                        href="mailto:{{ email }}?subject=A bug on {{ domain }}&body=first line\nsecond line\nthird line %3Cimg+src%3D%27newiibwhite.gif%27++%2F%3E">this
                    link</a> to open the email in your mail program. If you use Gmail, you can use this extension.</p>
            {% endif %}
            <h1>Invite a company and get +5 points when they join</h1>
            <label>Email:</label>
            <form role="form" action="/invite/" method="post" class="form-inline">
                {% csrf_token %}
                <input class="form-control" type="text" name="email">
                <button type="submit" class="btn btn-danger">Invite</button>
            </form>
        </div>
    </div>
{% endblock %}

website/templates/leaderboard.html
{% extends "base.html" %}
{% load gravatar %}

{% block style %}
    .list-group-item img {
    width: 50px;
    height: 50px;
    }
    .list-group-item .badge {
    margin-top: 15px;
    }
    .list-group-item a {
    text-decoration: none;
    margin-left: 10px;
    }
    .silver {
    background-color: lightblue;
    color: #333;
    }
    .gold {
    background-color: #D4AF37;
    color: #333;
    }
    .bronze {
    background-color: #C9AE5D;
    color: #333;
    }

{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <h1 class="page-header">Global Leaderboard</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-9">
            <div class="list-group">
                {% for leader in leaderboard %}
                    <div class="list-group-item">
                        {% if leader.userprofile.avatar %}
                            <img src="{{ leader.userprofile.avatar }}" class="img-responsive img-thumbnail">
                        {% elif leader.socialaccount_set.all.0.get_avatar_url %}
                            <img src="{{ leader.socialaccount_set.all.0.get_avatar_url }}">
                        {% else %}
                            <img src="{% gravatar_url leader.email 50 %}">
                        {% endif %}
                        <a href="/profile/{{ leader.username }}">{{ leader.username }}</a>
                        <span class="pull-right badge">{{ leader.total_score }} Points</span>
                        {% if leader.userprofile.winnings %}
                            <span class="pull-right badge">${{ leader.userprofile.winnings|default:""|floatformat }}</span>
                        {% endif %}

                        <span><kbd
                                class="{{ leader.userprofile.get_title_display }}">{{ leader.userprofile.get_title_display }}</kbd></span>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

website/templates/social.html
{% extends "account/base.html" %}

{% load i18n %}

{% block title %}Social Feeds - Bugheist{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <a class="twitter-timeline" data-height="800" href="https://twitter.com/Bugheist"></a>
            <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
    </div>
{% endblock %}